#!/bin/sh


if [ $2 == "y" ]; then
	vec=''
else
	vec='-fno-tree-vectorize'
fi

gcc -O"$1" $vec -march=native -mtune=native -Wall -I. -Isubroutines -DKAT -DKATNUM=${KAT} "-DCRYPTO_NAMESPACE(x)=x" "-D_CRYPTO_NAMESPACE(x)=_##x" -o kat nist/kat_kem.c nist/rng.c benes.c bm.c controlbits.c decrypt.c encrypt.c fft.c fft_tr.c gf.c operations.c pk_gen.c sk_gen.c vec.c  -L${PWD}/libs/lib_x86/ -lkeccak -lcrypto -ldl 
